apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmaira-redhat/argocd-promotion-demo.git'
    path: overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmaira-redhat/argocd-promotion-demo.git'
    path: overlays/test
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmaira-redhat/argocd-promotion-demo.git'
    path: overlays/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true