apiVersion: v1
kind: Namespace
metadata:
  name: demo-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    env: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-test
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    env: testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-prod
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    env: production