resources:
  - ../../base
namePrefix: dev-

# 1. This updates the image tag
images:
  - name: quay.io/libpod/alpine
    newName: registry.access.redhat.com/ubi9/ubi-minimal
    newTag: "9.3"  # Update this tag during the demo to show promotion

# 2. This injects the "dev" identity into the pod
patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "dev"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "registry.access.redhat.com/ubi9/ubi-minimal:9.3"