apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: quay.io/libpod/alpine:latest
        # This command now prints the variable
        command: ["/bin/sh", "-c", "while true; do echo \"hello - i am ${ENV_NAME}\"; sleep 10; done"]
        env:
        - name: ENV_NAME
          value: "unconfigured" # Default value
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"