apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: quay.io/libpod/alpine # Kustomize will replace this
        command: ["/bin/sh", "-c", "while true; do echo \"hello - i am ${ENV_NAME}, i been served using the image : ${IMAGE_INFO}\"; sleep 10; done"]
        env:
        - name: ENV_NAME
          value: "default"
        - name: IMAGE_INFO
          value: "unknown"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"